Feature/responsiveness
skyv26/portfolio pull request #15
Opened 2022-07-07 18:59 UTC by skyv26

# ⭐ Achievements

In my personal portfolio project I have added the html skeleton and css properties in order to completer my desktop version.
In this repository I have added the features which are as following:

- I have successfully added the both Mobile Version and Desktop Version Responsiveness in my portfolio.
- Portfolio is made with the help of Grid, Flexbox, Positioning Properties and many more other things.
- Added the background images in order to make exact clone of portfolio.
- Successfully debugged the html and css using linters
- Updated my README.md file with screenshots in order to get sneak peek of my work.

2022-07-07 20:41 UTC, BertrandConxy requested changes
Hi @skyv26 , 

Good job so far! 👏  🔥 
I really liked your work, from the clean codebase to the outstanding design, you really have done the best. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💪 
- Professional README
- Descriptive PR
- good commit messages
- Best UI/design
- Clean codebase

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-07 20:41 UTC, BertrandConxy commented on style.css
>  }
- [ ] I really appreciate your great work 👏, your work really blew my mind 🚀 🔥. Everything is fine. However, there is a little thing that you forgot to add that I think is very important. In your project cards, when someone hovers on each of the projects, the overlay texts disappear and the `See project ` appears. Try to look at the Figma design below, I think it will help you understand my point
![image](https://user-images.githubusercontent.com/90222110/177865782-e1e1ac3f-a8b2-4e1c-a1e8-6310cf8c2992.png)
This first project card shows how it should appear when someone hovers on each of your project cards. Ofcaurse, when he/she hovers on any of them, he/she will see the `see project` button. I think it is an important thing that should be implemented. Let me hope that this helps you to understand what I mean 😃 🚀

2022-07-07 20:55 UTC, skyv26 commented on style.css
>  }
But I think it requires JavaScript and according to project requirements I don't have to use JavaScript. I could be able to use JavaScript but still I am not at that level or following microverse requirements. Can you please help me by let me know about what should I do ?

2022-07-08 10:19 UTC, skyv26 commented on style.css
>  }
Thank you very much for pointing out the issue and I am really happy that I have successfully implemented the things as you suggest me with CSS only. 😄

2022-07-08 10:21 UTC, Kandy-Peter approved these changes
Hi @skyv26,

### APPROVED 🟢 

Great implementation of all the requirements in this milestone. 👏
Your web app looks really fantastic. 🎉 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

##  Optional suggestion

- [ ] OPTIONAL: It would be better if you enlarge your section's height. Their heights are too small. You can increase to make them take, each one, the all-screen size on non-scroll.

 
# CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-08 11:22 UTC, merged